version: '3.8'

services:
  postgresql:
    image: postgres:16
    container_name: postgresql
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 3s
      timeout: 5s

  flyway:
    image: flyway/flyway:10-alpine
    container_name: flyway
    restart: on-failure
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - .\app\migrations:/flyway/sql
    networks:
      - backend
    environment:
      FLYWAY_URL: jdbc:postgresql://postgresql:5432/postgres
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: postgres
      FLYWAY_BASELINE_ON_MIGRATE: "true"
    command: migrate
    healthcheck:
      test: ["CMD", "flyway", "info"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresql: {}
networks:
  backend: {}